### PR TITLE
Build a React Calculator app -Milestone1

### PR DESCRIPTION
**Pull request by ampaire**
This milestone contains the setup files for the react calculator app as stated in the [project requirements](https://github.com/microverseinc/project-react-calculator/blob/master/milestones/MILESTONE_1.md).

### CODE REVIEW

**Review by jofer86 — CHANGES_REQUESTED** [review]
## :wave: :wave: Hello!, I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- The only required change is to delete all of the unnecessary files, serviceworker, logo, test files, all of the code that is not going to be used should not be present, please do make the required change and do ask for another code review.

# `status: changes required` :rotating_light: :rotating_light: :rotating_light: 
--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

**Comment by ampaire** [comment]
Thank you @jofer86, let me get this done. I have however not seen the optional features that you are talking about

**Review by shloch — APPROVED** [review]
accomplished
You can merge this...great job

**Comment by ampaire** [comment]
Thank You @shloch

**Pull request merged**
