### PR TITLE
Revert "Build a react calculator app - Milestone three (Styling)"

### PR DESCRIPTION
**Pull request by ampaire**
Reverts ampaire/react-calculator#4

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @ampaire  :clap: 

### I trust you can fix the issue, I saw you made the correction in your previous branch but seems like you deleted them here, kindly fix it.

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by ampaire** [comment]
Hello @bellom, I  had merged this milestone but when I went to fill the completion form, I found that I needed to submit for another code review before submitting again. I then decided to revert it and I think that's where the issue came from

**Comment by bellom** [comment]
Hi @ampair, opps sorry for not approving then, next time you should drop a kinda message for the TSE to take note.
All look good, it should be approved now 👍

**Comment by ampaire** [comment]
Thank you so much, I take your advise and I will do just that should it happen again in the future. The status of the project is still on  **Changes requested** though.

**Comment by bellom** [comment]
@ampaire any new update?

**Comment by ampaire** [comment]
I am sooooo sorry I didn't get back to you after it was resolved.

Thanks for your help. The issue was resolved and the PR was approved.

Thanks so much

**Pull request closed without merging**
